<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="bunit" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\TacticalHeroes.Admin.Shared\TacticalHeroes.Admin.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Bunit" />
        <Using Include="Shouldly" />
        <Using Include="Xunit" />
    </ItemGroup>
</Project>
