<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PANiXiDA.Core.Ef.Migrator" />
    <ProjectReference Include="../../src/TacticalHeroes.Admin/TacticalHeroes.Admin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Migrator.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
