<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
		<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
		<PackageReference Include="MudBlazor" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Modules\TacticalHeroes.Admin.Modules.Compendium\TacticalHeroes.Admin.Modules.Compendium.csproj" />
		<ProjectReference Include="..\Modules\TacticalHeroes.Admin.Modules.Identity\TacticalHeroes.Admin.Modules.Identity.csproj" />
		<ProjectReference Include="..\TacticalHeroes.Admin.Api\TacticalHeroes.Admin.Api.csproj" />
		<ProjectReference Include="..\TacticalHeroes.Admin.Shared\TacticalHeroes.Admin.Shared.csproj" />
	</ItemGroup>

</Project>
