<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="PANiXiDA.Core.ResultPattern" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="PANiXiDA.Core.ResultPattern" />
    <Using Include="TacticalHeroes.Admin.Shared.Errors" />
    <Using Include="TacticalHeroes.Admin.Shared.Model" />
    <Using Include="TacticalHeroes.Admin.Shared.Navigation" />
    <Using Include="TacticalHeroes.Admin.Shared.Ui.Common" />
    <Using Include="TacticalHeroes.Admin.Shared.Validation" />
  </ItemGroup>

</Project>
